spring:

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: c##book_ex
    password: book_ex
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  
  secret: security-jwtsecurity-jwtsecurity-jwtsecurity-jwtsecurity-jwtsecurity-jwtsecurity-jwtsecurity-jwtsecurity-jwt
  accessToken-validity-in-seconds: 604800 #86400 #일주일
  refreshToken-validity-in-seconds: 86400 #24시간

logging:
  level:
    my.com.app: DEBUG
    
mybatis:   
  # 패키지 명을 생략할 수 있도록 alias 설정
  type-aliases-package: com.my.app.entity
  mapper-locations: com/my/app/mapper/*.xml
  
#Disabling White-label Error Page
server:
  error:
    whitelabel:
      enabled: false

#server:
#  port: 8081
#  